# Ultra-minimal GitLab CI for air-gapped environments
# If your GitLab runner doesn't have ANY docker images, use this version

pages:
  stage: deploy
  script:
    - cp -r gitlab-public public
  artifacts:
    paths:
      - public
  only:
    - main
    - gitlab